<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>App_Plugins</StaticWebAssetBasePath>
    <ContentTargetFolders>.</ContentTargetFolders>
    <Product>Umbraco.Community.DeliveryApiModelMapper</Product>
    <PackageId>Umbraco.Community.DeliveryApiModelMapper</PackageId>
    <Title>DeliveryApiModelMapper</Title>
    <Description>...</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <RootNamespace>Umbraco.Community.DeliveryApiModelMapper</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>16.0.0</Version>
    <Authors>Tristan Thompson</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Tristan Thompson</Copyright>
    <PackageProjectUrl>https://github.com/Gibe/Umbraco.Community.DeliveryApiModelMapper</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Gibe/Umbraco.Community.DeliveryApiModelMapper</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <!-- min 13.3.0 so that we can extend ApiContentResponseBuilder -->
    <PackageReference Include="Umbraco.Cms.Core" Version="16.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="16.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Delivery" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
